language: node_js
node_js:
  - "lts/*"

cache: yarn
before_install:
install:
  - yarn install
script:
  - yarn test
  - yarn build
after_success:
  - npm run lh -- https://staging.gatsby.patelrikin.com
