[build]
  publish = "public/"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[context.deploy-preview]
  publish = "public/"
  TRAVIS_PULL_REQUEST_SLUG = DEPLOY_PRIME_URL
  command = "npm run build && npm run lh -- ${DEPLOY_PRIME_URL}"
